UOE-11349: Update Lineitemtype
PubMatic-OpenWrap/dfp-prebid-setup pull request #50
Opened 2024-10-21 07:39 UTC by pm-isha-bharti

2024-10-21 08:11 UTC, Pubmatic-Dhruv-Sonone approved these changes

2024-10-21 09:07 UTC, Pubmatic-Dhruv-Sonone requested changes

2024-10-21 09:07 UTC, Pubmatic-Dhruv-Sonone commented on tasks/update.py
> +        UpdateUtils.print_skipped_line_items(skip_line_items)
Do we need this function?

2024-10-21 09:07 UTC, Pubmatic-Dhruv-Sonone commented on tasks/update.py
> +            self.logger.info("No line items matched the criteria for update.")
Can we make this a separate function?  `VideoPositionUpdater` also have similar update code.

2024-10-21 09:14 UTC, Pubmatic-Dhruv-Sonone commented on tasks/update.py
> +            line_items_with_current_type[line_item['name']]=current_type
Should this be `lineItemType` instead of 'name'?

2024-10-21 09:26 UTC, Pubmatic-Dhruv-Sonone commented on tasks/update.py
> +        self.print_line_items_with_current_type(line_items_with_current_type)
Why do we need to print this?

2024-10-21 09:33 UTC, pm-isha-bharti commented on tasks/update.py
> +        UpdateUtils.print_skipped_line_items(skip_line_items)
Not required, will remove

2024-10-22 05:29 UTC, Pubmatic-Dhruv-Sonone approved these changes

2024-11-06 11:21 UTC, merged